FROM golang:1.23 AS build
WORKDIR /
COPY . .
RUN go mod download && go mod verify
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /cmd/api
RUN CGO_ENABLED=1 go build -gcflags "all=-N -l" -o ./app
ENTRYPOINT ["dlv"]
CMD ["--listen=:2345", "--headless=true", "--api-version=2", "--log", "exec", "app"]
